profile_id:
  comment: Sequential profile number within the trajectory. This value is unique in each file that is part of a single trajectory/deployment.
  long_name: 'Profile ID'
  valid_max: '2147483647'
  valid_min: '1'

profile_time:
  comment:           Timestamp corresponding to the mid-point of the profile
  long_name:         Profile Center Time
  observation_type:  calculated
  platform:          platform
  standard_name:     time
  units:             seconds since 1970-01-01T00:00:00Z

profile_time_start:
  comment:           Timestamp corresponding to the start of the profile
  long_name:         Profile Start Time
  observation_type:  calculated
  platform:          platform
  standard_name:     time
  units:             seconds since 1970-01-01T00:00:00Z

profile_time_end:
  comment:           Timestamp corresponding to the end of the profile
  long_name:         Profile End Time
  observation_type:  calculated
  platform:          platform
  standard_name:     time
  units:             seconds since 1970-01-01T00:00:00Z

profile_lat:
  comment:           Value is interpolated to provide an estimate of the latitude at the mid-point of the profile
  long_name:         Profile Center Latitude
  observation_type:  calculated
  platform:          platform
  standard_name:     latitude
  units:             degrees_north
  valid_max:         "90.0"
  valid_min:         "-90.0"

profile_lon:
  comment:           Value is interpolated to provide an estimate of the latitude at the mid-point of the profile
  long_name:         Profile Center Longitude
  observation_type:  calculated
  platform:          platform
  standard_name:     longitude
  units:             degrees_east
  valid_max:         "180.0"
  valid_min:         "-180.0"

u:
  comment:  The depth-averaged current is an estimate of the net current measured while the glider is underwater.  The value is calculated over the entire underwater segment, which may consist of 1 or more dives.
  long_name:         Depth-Averaged Eastward Sea Water Velocity
  observation_type:  calculated
  platform:          platform
  standard_name:     eastward_sea_water_velocity
  units:             m s-1
  valid_max:         "10.0"
  valid_min:         "-10.0"

v:
  comment:  The depth-averaged current is an estimate of the net current measured while the glider is underwater.  The value is calculated over the entire underwater segment, which may consist of 1 or more dives.
  long_name:         Depth-Averaged Northward Sea Water Velocity
  observation_type:  calculated
  platform:          platform
  standard_name:     northward_sea_water_velocity
  units:             m s-1
  valid_max:         "10.0"
  valid_min:         "-10.0"

lon_uv:
  comment:           Not computed
  long_name:         Longitude
  observation_type:  calculated
  platform:          platform
  standard_name:     longitude
  units:             degrees_east
  valid_max:         "180.0"
  valid_min:         "-180.0"

lat_uv:
  comment:           Not computed
  long_name:         Latitude
  observation_type:  calculated
  platform:          platform
  standard_name:     latitude
  units:             degrees_north
  valid_max:         "90.0"
  valid_min:         "-90.0"

time_uv:
  comment:       Not computed
  long_name:     Time
  standard_name: time
  calendar:      gregorian
  units:         seconds since 1970-01-01T00:00:00Z
  observation_type: calculated

